eureka:
  client:
    serviceUrl:
      defaultZone: http://www.chauncywang.com:8888/eureka/
server:
  port: 8777
spring:
  application:
    name: SpringCloud-Feign
feign:
  hystrix:
    enabled: true
    